### ISSUE TITLE
General: The NGGallery galleries are styled wrong

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Sutdweld-International#54]
http://studweldinternational.stage.titanweb.com.au/about-us/

Check the knowledgebase for more information.

**Comment by bernardtitan** [comment]
The galleries should have pagination after the 25th item

**Comment by genesiscebudigital** [comment]
https://knowledgebase.titanweb.com.au/implementation-practices/nggallery-implementation-practices/gallery-layout-and-styles

**Comment by bernardtitan** [comment]
Refer to the comment above yours.
